# -------------------------- FUNCTION: GENERATE RESEARCH QUERY
[functions.generate_research_query]
type = "chat"

[functions.generate_research_query.variants.gpt_4o_mini]
type = "chat_completion"
model = "openai::gpt-4o-mini"
system_template = "functions/generate_research_query/simple_variant/system.minijinja"
user_template = "functions/generate_research_query/simple_variant/user.minijinja"

# -------------------------- FUNCTION: SYNTHESISE CONTENT
# Function
[functions.synthesise_content]
type = "chat"

# Variant 1
[functions.synthesise_content.variants.gpt_4o_mini]
weight = 0.7
type = "chat_completion"
model = "openai::gpt-4o-mini"
system_template = "functions/synthesise_content/gpt_4o_mini_variants/system.minijinja"
user_template = "functions/synthesise_content/gpt_4o_mini_variants/user.minijinja"

# Variant 2
[functions.synthesise_content.variants.haiku_variant]
type = "chat_completion"
weight = 0.3
model = "my_haiku_3"
system_template = "functions/synthesise_content/haiku_variant/system.minijinja"
user_template   = "functions/synthesise_content/haiku_variant/user.minijinja"
temperature     = 0.9

# Models
[models.my_haiku_3]
routing = ["my_anthropic_provider"]  # ✅ REQUIRED

[models.my_haiku_3.providers.my_anthropic_provider]
type = "anthropic"
model_name = "claude-3-haiku-20240307"



# Metrics
[metrics.synthesis_quality]
type = "float"
optimize = "max"
level = "inference"

[metrics.user_rating]
type = "float"
optimize = "max"
level = "episode"