# -------------------------- FUNCTION: THREAD IDEAS
[functions.thread_ideas]
type = "json"
user_schema = "functions/thread_ideas/user_schema.json"
output_schema = "functions/thread_ideas/output_schema.json"

[functions.thread_ideas.variants.gpt_4o_mini]
type = "chat_completion"
model = "openai::gpt-4o-mini"
system_template = "functions/thread_ideas/claude_variant/system.minijinja"
user_template = "functions/thread_ideas/claude_variant/user.minijinja"
json_mode = "strict"

[functions.thread_ideas.variants.claude_sonnet]
type = "chat_completion"
model = "my_claude_sonnet"
system_template = "functions/thread_ideas/claude_variant/system.minijinja"
user_template = "functions/thread_ideas/claude_variant/user.minijinja"
json_mode = "strict"

# -------------------------- FUNCTION: SYNTHESISE CONTENT
# Function
[functions.synthesise_content]
type = "json"
user_schema = "functions/synthesise_content/user_schema.json"
output_schema = "functions/synthesise_content/output_schema.json"

# Variant 1
[functions.synthesise_content.variants.gpt_4o_mini]
weight = 0.7
type = "chat_completion"
model = "openai::gpt-4o-mini"
system_template = "functions/synthesise_content/gpt_4o_mini_variants/system.minijinja"
user_template = "functions/synthesise_content/gpt_4o_mini_variants/user.minijinja"
json_mode = "strict"

# Variant 2
[functions.synthesise_content.variants.haiku_variant]
type = "chat_completion"
weight = 0.3
model = "my_haiku_3"
system_template = "functions/synthesise_content/haiku_variant/system.minijinja"
user_template   = "functions/synthesise_content/haiku_variant/user.minijinja"
temperature     = 0.9
json_mode = "strict"

# -------------------------- MODELS
[models.my_haiku_3]
routing = ["my_anthropic_provider"]

[models.my_haiku_3.providers.my_anthropic_provider]
type = "anthropic"
model_name = "claude-3-haiku-20240307"

[models.my_claude_sonnet]
routing = ["my_anthropic_provider"]

[models.my_claude_sonnet.providers.my_anthropic_provider]
type = "anthropic"
model_name = "claude-3-5-sonnet-20241022"


# -------------------------- METRICS
[metrics.synthesis_quality]
type = "float"
optimize = "max"
level = "inference"

[metrics.user_rating]
type = "float"
optimize = "max"
level = "episode"