# A function defines the task we're tackling (e.g. generating a haiku)...
[functions.synthesise_content]
type = "chat"

# ... and a variant is one of many implementations we can use to tackle it (a choice of prompt, model, etc.).
# Since we only have one variant for this function, the gateway will always use it.
[functions.synthesise_content.variants.gpt_4o_mini]
type = "chat_completion"
model = "openai::gpt-4o-mini"
system_template = "functions/synthesise_content/gpt_4o_mini_variants/system.minijinja"
user_template = "functions/synthesise_content/gpt_4o_mini_variants/user.minijinja"

# Define metric to keep track of quality of the synthesis
[metrics.synthesis_quality]
type = "float"
optimize = "max"
level = "inference"